version: '3'

services:
  service_monitor:
    image: service-monitor:latest
    build:
        context: ./
        dockerfile: ./Dockerfile
    dns:
      - 1.1.1.1
    ports:
        - 8080:8080
    command: /usr/local/bin/service-monitor ./example/sample.csv --log-level DEBUG