version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3.7
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip3 install -r requirements-develop.txt
        - run:
            name: run flake8
            command: |
              . venv/bin/activate
              flake8
        - run:
            name: run tests
            command: |
                . venv/bin/activate
                pytest
        - run:
            name: Build application Docker image
            command: |
                docker build -t service-monitor .
        - deploy:
            name: Push application Docker image
            command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                login="$(aws ecr get-login)"
                ${login}
                docker tag service-monitor "${ECR_ENDPOINT}/service-monitor:${CIRCLE_SHA1}"
                docker push "${ECR_ENDPOINT}/service-monitor:${CIRCLE_SHA1}"
                fi